version: "3"

services:
    database:
        # https://hub.docker.com/_/postgres/
        image: postgres:16.1-alpine
        restart: always
        env_file: .env
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        hostname: ${DB_HOSTNAME}
        ports:
            - "${DB_HOSTNAME}:${DB_PORT}:${DB_PORT}"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
